### ISSUE TITLE
Breakfast Club S02E03: Back to where it's cozy

### ISSUE THREAD

**Issue by Ilidur** [breakfast-club-oxford/event-organisation#10]
Venue: Society Cafe, St. Michael's St.
When: Friday Oct 13th, 8:00am - 9:30am.

**Comment by thisjunewest** [comment]
This happened?

**Comment by javorszky** [comment]
Yes, I was there. @Ilidur has like, one image

**Comment by Ilidur** [comment]
There!

![img_20171013_092231038](https://user-images.githubusercontent.com/988494/32020754-20f4eade-b9c9-11e7-911e-c36964e17209.jpg)
