### ISSUE TITLE
Breakfast Club S02E04: Organise it yourself, Max

### ISSUE THREAD

**Issue by thisjunewest** [breakfast-club-oxford/event-organisation#11]
Venue: The Handlebar Cafe in Oxford
When: Oct 27nd, 8:00am - 9:30am.

The Handlebar Cafe on St Michaels street: https://www.handlebaroxford.co.uk/

**Comment by omgmog** [comment]
![](https://media3.giphy.com/media/zPOErRpLtHWbm/giphy.gif)

**Comment by javorszky** [comment]
![img_20171027_085530](https://user-images.githubusercontent.com/1196299/32096585-cab0b7b6-bafe-11e7-8473-7237c17c6ce5.jpg)

Today was a success! Attendance was up 50%! Thank you @peterjwest @Ilidur for coming! :)

**Comment by thisjunewest** [comment]
Why is that mirrored? It's messing with my head
