### ISSUE TITLE
Breakfast Club #3: #Breakfast #with #a #vengeance

### ISSUE THREAD

**Issue by spikeheap** [breakfast-club-oxford/event-organisation#3]
Venue: [Society Cafe, Oxford](https://www.google.co.uk/maps/place/Society+Caf%C3%A9+Oxford/@51.7534829,-1.2592914,15z/data=!4m2!3m1!1s0x0:0xa172c383e4e9f944?sa=X&ved=0ahUKEwiOrOK7_a3TAhXHLsAKHeLtDFcQ_BIIdjAK)
When: May 5th, 7:30am - 9:30am. 
---

Different venue again, to keep you on your toes. Society Café on St Michaels street: http://www.society-cafe.com/.

__This time we're meeting a little earlier,__ so all you crazy people who have jobs to get to can come along 🥐.

What better way to end a short week than with an early morning chat over coffee before work?

As always, we'll be on the Digital Oxford Slack in #breakfastclub to plan and keep track of numbers.

**Comment by omgmog** [comment]
Not _that's_ how you name an event!

**Comment by spikeheap** [comment]
This happened. It was totally a thing. And it was awesome. We talked about:
- International law (because morning)
- Throat microphones
- Magnets, Bluetooth, NFC, and hardware hacking
- Learning Japanese (https://www.wanikani.com/)
- Electrocuting people for fun (and being added to a bomb-threat list)
![img_2714](https://cloud.githubusercontent.com/assets/464482/25755769/202f5250-31bc-11e7-8342-584ca9215e7e.jpg)

and about how I didn't buy everyone breakfast

Lots of business-value was had. There were ties:
![img_20170505_084817](https://cloud.githubusercontent.com/assets/464482/25755657/bce81290-31bb-11e7-8490-92bbcfb4842a.jpg)

![](https://pbs.twimg.com/media/C_C5TdBW0AI__00.jpg)

and business cards:

![](https://pbs.twimg.com/media/C_C5k5bXoAAFmYj.jpg)

![](https://pbs.twimg.com/media/C_C5mK8XcAE9aNJ.jpg)

and a bit of hacking and remote working
![img_20170505_112920](https://cloud.githubusercontent.com/assets/464482/25755717/f66bc192-31bb-11e7-9d2e-c2004f27fc16.jpg)

Kudos to Marcus, Gabor & Adam for the photos

**Comment by spikeheap** [comment]
Also, Society Cafe was a great venue. They're always super-friendly and have great coffee. The only downside was that an almond croissant, whilst tasty, doesn't cut the mustard as a full breakfast.

**Comment by omgmog** [comment]
:100: top breakfasting folks!
