### ISSUE TITLE
Breakfast Club #4: The Voyage to Breakfast #hashtagbreakfasttime

### ISSUE THREAD

**Issue by spikeheap** [breakfast-club-oxford/event-organisation#4]
Venue: [Art Cafe, Oxford](https://www.google.co.uk/maps/place/Art+Cafe/@51.7516927,-1.2603067,15z/data=!4m2!3m1!1s0x0:0xa076d20f99ccfb99?sa=X&ved=0ahUKEwiWldv2nNnTAhWsDsAKHfAIC3oQ_BIIhwEwDg)
When: May 19th, 7:30am - 9:30am. 
---

We're still changing things up. Meeting at the [Art Cafe](http://www.artcafeoxford.co.uk/site/) by Bonn Square. They have a variety of breakfast options. 

Art Cafe opens at 7am, so feel free to turn up early if you're super keen. I'm looking at you @ AverageMarcus.

What better way to end a short week than with an early morning chat over coffee before work?

As always, we'll be on the Digital Oxford Slack in #breakfastclub to plan and keep track of numbers.

**Comment by Rumyra** [comment]
YES!!

**Comment by spikeheap** [comment]
I'm pretty excited that @Rumyra can make it. I'll need to shoot off around 9-9:30 this time round

**Comment by Rumyra** [comment]
What the 

@spikeheap WHEN ARE WE GOING TO OUTDOOR SWIM IF NOT AFTER BREAKFAST CLUB!

😂

**Comment by spikeheap** [comment]
How about on Saturday before the barbecue @Rumyra?

**Comment by omgmog** [comment]
This happened, early mornings did not defeat all of us.

The Art Cafe was a nice venue. They had coffee, but didn't have avocados.

We talked about things:
- VR (obviously)
- Google superseding Pete's plans to do positional tracking
- Ties.
- Jeans
- Burnt hair.

![img_20170519_084851](https://cloud.githubusercontent.com/assets/50949/26250183/2d01e46c-3ca1-11e7-8449-9c15fca7039e.jpg)
![img_20170519_084903](https://cloud.githubusercontent.com/assets/50949/26250185/2d030a86-3ca1-11e7-96bd-3375c07b3ef7.jpg)
![img_20170519_084912](https://cloud.githubusercontent.com/assets/50949/26250184/2d02f6ae-3ca1-11e7-82dc-556af2b28520.jpg)

Following the breakfast club meetup, we also held an impromptu #brunchclub back at the Handlebar Cafe, and then #lunchcoffeeclub back at the Society Cafe.
