### ISSUE TITLE
Breakfast club #7: Are you gonna plan all day, lil' doggie, or are you gonna come?

### ISSUE THREAD

**Issue by javorszky** [breakfast-club-oxford/event-organisation#7]
Reservoir dogs style. Because I am now in the possession of a very sizeable collection of ties that I am more than happy to share with folks.

Venue: Uh... I liked Society.
When: June 30th, 7:00am - 9:30am.
---

Potentially followed by Brunchcafé, Lunchcafé, and whatever else.

**Comment by javorszky** [comment]
The entire cast of today's breakfast club.

![2017-06-30 08 32 21](https://user-images.githubusercontent.com/1196299/27727566-e9aff8d8-5d76-11e7-8037-120af7f4c4b0.jpg)

We talked motorcycles, gear, protips around changing from casual to geared, bike security, bike insurance.

We then moved on to hackspace politics, general politics, people generally being irrational.

And finally about member management softwares, in case you want to run your own coworking space / hackspace. They are:

* https://www.cobot.me/ - built in Berlin by coworking office people to scratch their own itch
* https://cowork.io/
* https://www.getcroissant.com/ - cute name, it's also a coworking space network membership thing that tacks on your existing infrastructure to attract international workers
* https://www.mindbodyonline.com/ - if you want to run a wellness spa thing
* https://officernd.com/ - high-end of the market
* https://www.optixapp.com/ - super high-end, reflected in pricing
* http://www.nexudus.com/en - what the globe is running on, but it's getting complaints

Anyhow, until next time! :)

**Comment by spikeheap** [comment]
I love that the ties are still going. Gutted I've been away and not able to make the last few.

**Comment by javorszky** [comment]
I have a HUGE bag of ties ^_^. They're all amazing.
