### ISSUE TITLE
Breakfast Club S02E02: On the other side of town

### ISSUE THREAD

**Issue by Ilidur** [breakfast-club-oxford/event-organisation#9]
Venue: The Bear And The Bean, Cowley Rd.
When: Friday September 15th, 8:30am - 9:30am. 
---

Let's try a place closer to Ben. See if that encourages him to come.

P.S. Ties are still required.

**Comment by javorszky** [comment]
Did this happen?

**Comment by Ilidur** [comment]
![img_20170915_094727337](https://user-images.githubusercontent.com/988494/30806191-ad33e9c2-a1ec-11e7-9fe4-12f2de8ea193.jpg)
Proof!
